config/routes.rb
Cms::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  root :to => 'home#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :home do
    collection do
      get 'about'
    end
  end
  resources :klass, :path => "class"
  resources :subject
  resources :chapter
  resources :topics do
    member do
      get 'history'
    end
  end

  resources :questions do
    member do
      get 'history'
    end
  end

  resources :answers do
    member do
      get 'history'
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  has_paper_trail
  attr_accessible :description, :question_id
  belongs_to :question
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	has_paper_trail
  attr_accessible :title, :name, :description, :subject_id
  belongs_to :subject
  has_many :topics

  validates_presence_of :subject_id
  validates_uniqueness_of :name, :scope => :subject_id
end

app/models/klass.rb
class Klass < ActiveRecord::Base
	has_paper_trail
  attr_accessible :title, :name
  has_many :subjects
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_paper_trail
  attr_accessible :title, :topic_id
  belongs_to :topic
  has_many :answers
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_paper_trail
  attr_accessible :title, :name, :klass_id
  belongs_to :klass
  has_many :chapters

  validates_presence_of :klass_id
  validates_uniqueness_of :name, :scope => :klass_id
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_paper_trail
  # attr_accessible :title, :body
  attr_accessible :title, :name, :description, :chapter_id
  belongs_to :chapter
  has_many :questions
  validates_presence_of :chapter_id, :blank => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base
	def history
		@answer = Answer.find(params[:id])
	end
end

app/controllers/chapter_controller.rb
class ChapterController < ApplicationController
	add_breadcrumb "home", :root_path
	add_breadcrumb "class", :klass_path

	def show
		@chapter = Chapter.find(params[:id])
		add_breadcrumb @chapter.subject.klass.name, klas_path(@chapter.subject.klass)
		add_breadcrumb @chapter.subject.name, subject_path
		add_breadcrumb @chapter.name, chapter_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/klass_controller.rb
class KlassController < ApplicationController
	add_breadcrumb "home", :root_path
	
	def index
		logger.info params
		logger.info cookies

		@klasses = Klass.all
		add_breadcrumb "class", klass_path
	end

	def show
		@klass = Klass.find(params[:id])
		add_breadcrumb "class", klass_path
		add_breadcrumb @klass.name, klas_path(@klass)
	end
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
	def history
		@question = Question.find(params[:id])
	end
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController
	add_breadcrumb "home", :root_path
	add_breadcrumb "class", :klass_path

	def show
		@topic = Topic.find(params[:id])
		add_breadcrumb @topic.chapter.subject.klass.name, klas_path(@topic.chapter.subject.klass)
		add_breadcrumb @topic.chapter.subject.name, subject_path(@topic.chapter.subject)
		add_breadcrumb @topic.chapter.name, chapter_path(@topic.chapter)
		add_breadcrumb @topic.name, topic_path
	end

	def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
    end
	 end


	def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
	 end

	# GET /users/1/edit
	def edit
		@topic = Topic.find(params[:id])
	end

	def update
	    @topic = Topic.find(params[:id])

	    respond_to do |format|
	      if @topic.update_attributes(params[:topic])
	        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
	      else
	        format.html { render action: "edit" }
	      end
	    end
	end

	def history
		@topic = Topic.find(params[:id])
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	add_breadcrumb "home", :root_path
	add_breadcrumb "class", :klass_path

	def show
		@topic = Topic.find(params[:id])
		add_breadcrumb @topic.chapter.subject.klass.name, klas_path(@topic.chapter.subject.klass)
		add_breadcrumb @topic.chapter.subject.name, subject_path(@topic.chapter.subject)
		add_breadcrumb @topic.chapter.name, chapter_path(@topic.chapter)
		add_breadcrumb @topic.name, topic_path
	end

	def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
    end
	 end


	def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
	 end

	# GET /users/1/edit
	def edit
		@topic = Topic.find(params[:id])
	end

	def update
	    @topic = Topic.find(params[:id])

	    respond_to do |format|
	      if @topic.update_attributes(params[:topic])
	        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
	      else
	        format.html { render action: "edit" }
	      end
	    end
	end

	def history
		@topic = Topic.find(params[:id])
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def app_title title
		"<div id='page-title'>
		  <div id='page-title-inner'>
		    <div class='container'>
		      <h2><i class='ico-stats ico-white'></i>#{title}</h2>
		    </div>
		  </div>  
		</div>".html_safe
	end
end

app/helpers/chapter_helper.rb
module ChapterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/klass_helper.rb
module KlassHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :topic_id %><br />
    <%= f.number_field :topic_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/history.html.erb
<%= app_title("Question History")%>

<!--start: Wrapper-->
<div id="wrapper">
  <!--start: Container -->
  <div class="container">
    <!--start: Row -->
    <div class="row">
      <div class="span8">
      	<% @question.versions.each_with_index do |version, index| %>
          <% question = version.reify %>
          <div id="about">
            <p>
              <%= question.title if question %>
            </p>
          </div>
        <% end %>
      </div>
      <div class="span4">
        <!-- start: Sidebar -->
        <%= render "klass/sidebar" %>
        <!-- end: Sidebar -->
      </div>
    </div>
    <!--end: Row-->
  </div>
  <!--end: Container-->
</div>
<!-- end: Wrapper  -->

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Topic</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.title %></td>
    <td><%= question.topic_id %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<!--start: Page Title -->
<div id="page-title">
  <div id="page-title-inner">
    <!-- start: Container -->
    <div class="container">
      <h2><i class="ico-stats ico-white"></i>Question</h2>
    </div>
    <!-- end: Container  -->
  </div>  
</div>
<!-- end: Page Title -->

<!--start: Wrapper-->
<div id="wrapper">
  <!--start: Container -->
  <div class="container">
    <!--start: Row -->
    <div class="row">
      <div class="span8">
        <div class="title">
          <h3>Question:</h3>
          <%= link_to edit_question_path(@question), :class => "btn btn-mini", :style => "float:right;" do %>
            <i class="mini-ico-pencil"></i>
          <% end %>
          <%= link_to history_question_path(@question), :class => "btn btn-mini", :style => "float:right;" do %>
            <i class="mini-ico-list"></i>
          <% end %>
        </div>
        <h5>
        	<%= @question.title %>
        </h5>
        <div id="about">
          <div class="title">
            <h3>Answers</h3>
          </div>
          <div class="row">
            <ul class="nav nav-pills nav-stacked" style="float:left;">
              <% @question.answers.each do |answer| %>
                <%= link_to edit_answer_path(answer), :class => "btn btn-mini", :style => "float:right;" do %>
                  <i class="mini-ico-pencil"></i>
                <% end %>
                <%= link_to history_answer_path(answer), :class => "btn btn-mini", :style => "float:right;" do %>
                  <i class="mini-ico-list"></i>
                <% end %>
                <li>
                  <%= answer.description %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
      <div class="span4">
        <!-- start: Sidebar -->
        <%= render "klass/sidebar" %>
        <!-- end: Sidebar -->
      </div>
    </div>
    <!--end: Row-->
  </div>
  <!--end: Container-->
</div>
<!-- end: Wrapper 