config/routes.rb
Cms::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  root :to => 'home#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :home do
    collection do
      get 'about'
    end
  end
  resources :klass, :path => "class"
  resources :subject
  resources :chapter
  resources :topics do
    member do
      get 'history'
    end
  end

  resources :questions do
    member do
      get 'history'
    end
  end

  resources :answers do
    member do
      get 'history'
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  has_paper_trail
  attr_accessible :description, :question_id
  belongs_to :question
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	has_paper_trail
  attr_accessible :title, :name, :description, :subject_id
  belongs_to :subject
  has_many :topics

  validates_presence_of :subject_id
  validates_uniqueness_of :name, :scope => :subject_id
end

app/models/klass.rb
class Klass < ActiveRecord::Base
	has_paper_trail
  attr_accessible :title, :name
  has_many :subjects
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_paper_trail
  attr_accessible :title, :topic_id
  belongs_to :topic
  has_many :answers
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_paper_trail
  attr_accessible :title, :name, :klass_id
  belongs_to :klass
  has_many :chapters

  validates_presence_of :klass_id
  validates_uniqueness_of :name, :scope => :klass_id
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_paper_trail
  # attr_accessible :title, :body
  attr_accessible :title, :name, :description, :chapter_id
  belongs_to :chapter
  has_many :questions
  validates_presence_of :chapter_id, :blank => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/answers_controller.rb
class AnswersController < InheritedResources::Base
	def history
		@answer = Answer.find(params[:id])
	end
end

app/controllers/chapter_controller.rb
class ChapterController < ApplicationController
	add_breadcrumb "home", :root_path
	add_breadcrumb "class", :klass_path

	def show
		@chapter = Chapter.find(params[:id])
		add_breadcrumb @chapter.subject.klass.name, klas_path(@chapter.subject.klass)
		add_breadcrumb @chapter.subject.name, subject_path
		add_breadcrumb @chapter.name, chapter_path
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/klass_controller.rb
class KlassController < ApplicationController
	add_breadcrumb "home", :root_path
	
	def index
		logger.info params
		logger.info cookies

		@klasses = Klass.all
		add_breadcrumb "class", klass_path
	end

	def show
		@klass = Klass.find(params[:id])
		add_breadcrumb "class", klass_path
		add_breadcrumb @klass.name, klas_path(@klass)
	end
end

app/controllers/questions_controller.rb
class QuestionsController < InheritedResources::Base
	def history
		@question = Question.find(params[:id])
	end
end

app/controllers/subject_controller.rb
class SubjectController < ApplicationController
	add_breadcrumb "home", :root_path
	add_breadcrumb "class", :klass_path

	def show
		@subject = Subject.find(params[:id])
		add_breadcrumb @subject.klass.name, klas_path(@subject.klass)
		add_breadcrumb @subject.name, subject_path
	end
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController
	add_breadcrumb "home", :root_path
	add_breadcrumb "class", :klass_path

	def show
		@topic = Topic.find(params[:id])
		add_breadcrumb @topic.chapter.subject.klass.name, klas_path(@topic.chapter.subject.klass)
		add_breadcrumb @topic.chapter.subject.name, subject_path(@topic.chapter.subject)
		add_breadcrumb @topic.chapter.name, chapter_path(@topic.chapter)
		add_breadcrumb @topic.name, topic_path
	end

	def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
    end
	 end


	def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
	 end

	# GET /users/1/edit
	def edit
		@topic = Topic.find(params[:id])
	end

	def update
	    @topic = Topic.find(params[:id])

	    respond_to do |format|
	      if @topic.update_attributes(params[:topic])
	        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
	      else
	        format.html { render action: "edit" }
	      end
	    end
	end

	def history
		@topic = Topic.find(params[:id])
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	add_breadcrumb "home", :root_path
	add_breadcrumb "class", :klass_path

	def show
		@topic = Topic.find(params[:id])
		add_breadcrumb @topic.chapter.subject.klass.name, klas_path(@topic.chapter.subject.klass)
		add_breadcrumb @topic.chapter.subject.name, subject_path(@topic.chapter.subject)
		add_breadcrumb @topic.chapter.name, chapter_path(@topic.chapter)
		add_breadcrumb @topic.name, topic_path
	end

	def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
    end
	 end


	def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
	 end

	# GET /users/1/edit
	def edit
		@topic = Topic.find(params[:id])
	end

	def update
	    @topic = Topic.find(params[:id])

	    respond_to do |format|
	      if @topic.update_attributes(params[:topic])
	        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
	      else
	        format.html { render action: "edit" }
	      end
	    end
	end

	def history
		@topic = Topic.find(params[:id])
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def app_title title
		"<div id='page-title'>
		  <div id='page-title-inner'>
		    <div class='container'>
		      <h2><i class='ico-stats ico-white'></i>#{title}</h2>
		    </div>
		  </div>  
		</div>".html_safe
	end
end

app/helpers/chapter_helper.rb
module ChapterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/klass_helper.rb
module KlassHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.cktext_area :description, :ckeditor => {:uiColor => '#AADC6E', :toolbar => 'mini'} %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/_questions.html.erb
<div class="title">
  <h3>Questions</h3>
</div>
<% @topic.questions.each do |question| %>
	<p>
	  <%= link_to question.title, question_path(question) if !question.title.blank? %>
	</p>
<% end %>

app/views/topics/edit.html.erb
<%= app_title("Editing user")%>

<!--start: Wrapper-->
<div id="wrapper">
  <!--start: Container -->
  <div class="container">
    <!--start: Row -->
    <div class="row">
      <div class="span8">
      	<%= render 'form' %>
      </div>
      <div class="span4">
        <!-- start: Sidebar -->
        <%= render "klass/sidebar" %>
        <!-- end: Sidebar -->
      </div>
    </div>
    <!--end: Row-->
  </div>
  <!--end: Container-->
</div>
<!-- end: Wrapper  -->

app/views/topics/history.html.erb
<%= app_title("Topic History")%>

<!--start: Wrapper-->
<div id="wrapper">
  <!--start: Container -->
  <div class="container">
    <!--start: Row -->
    <div class="row">
      <div class="span8">
      	<% @topic.versions.each_with_index do |version, index| %>
          <% topic = version.reify %>
          <div id="about">
            <div class="title">
              <h3><%= topic.name %></h3>
            </div>
            <p>
              <%= @topic.description.html_safe %>
            </p>
          </div>
        <% end %>
      </div>
      <div class="span4">
        <!-- start: Sidebar -->
        <%= render "klass/sidebar" %>
        <!-- end: Sidebar -->
      </div>
    </div>
    <!--end: Row-->
  </div>
  <!--end: Container-->
</div>
<!-- end: Wrapper  -->

app/views/topics/index.html.erb
<!-- start: Page Title -->
<div id="page-title">
  <div id="page-title-inner">
    <!-- start: Container -->
    <div class="container">
      <h2><i class="ico-stats ico-white"></i>Classes</h2>
    </div>
    <!-- end: Container  -->
  </div>  
</div>
<!-- end: Page Title -->

<!--start: Wrapper-->
<div id="wrapper">
  <!--start: Container -->
  <div class="container">
    <!--start: Row -->
    <div class="row">
      <div class="span8">
        <!-- start: About Us -->
        <div id="about">
          <div class="title">
            <h3>Classes</h3>
          </div>
          <div class="row">
            <ul class="nav nav-pills nav-stacked" style="float:left;">
              <% @klasses.each do |klass| %>
                <li>
                  <%= link_to klass.name, klas_path(klass)%>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
        <!-- end: About Us -->
      </div>
      <div class="span4">
        <!-- start: Sidebar -->
        <%= render "klass/sidebar" %>
        <!-- end: Sidebar -->
      </div>
    </div>
    <!--end: Row-->
  </div>
  <!--end: Container-->
</div>
<!-- end: Wrapper  -->

app/views/topics/new.html.erb
<!--start: Page Title -->
<div id="page-title">
  <div id="page-title-inner">
    <!-- start: Container -->
    <div class="container">
      <h2><i class="ico-stats ico-white"></i>New Topic</h2>
    </div>
    <!-- end: Container  -->
  </div>  
</div>
<!-- end: Page Title -->

<!--start: Wrapper-->
<div id="wrapper">
  <!--start: Container -->
  <div class="container">
    <!--start: Row -->
    <div class="row">
      <div class="span8">
        <!-- start: About Us -->
        <div id="about">
          <div class="title">
            <h3>New Topic</h3>
          </div>
          <div> <%= render_breadcrumbs %> </div>
          <div class="row">
          	<%= render 'form' %>
          </div>
        </div>
        <!-- end: About Us -->
      </div>
      <div class="span4">
        <!-- start: Sidebar -->
        <%= render "klass/sidebar" %>
        <!-- end: Sidebar -->
      </div>
    </div>
    <!--end: Row-->
  </div>
  <!--end: Container-->
</div>
<!-- end: Wrapper 

app/views/topics/show.html.erb
<!--start: Page Title -->
<div id="page-title">
  <div id="page-title-inner">
    <!-- start: Container -->
    <div class="container">
      <h2><i class="ico-stats ico-white"></i>Topic</h2>
    </div>
    <!-- end: Container  -->
  </div>  
</div>
<!-- end: Page Title -->

<!--start: Wrapper-->
<div id="wrapper">
  <!--start: Container -->
  <div class="container">
    <!--start: Row -->
    <div class="row">
      <div class="span8">
        <!-- start: About Us -->
        <div id="about">
          <div class="title">
            <h3>Topic</h3>
            <%= link_to edit_topic_path(@topic), :class => "btn btn-mini", :style => "float:right;" do %>
              <i class="mini-ico-pencil"></i>
            <% end %>
            <%= link_to history_topic_path(@topic), :class => "btn btn-mini", :style => "float:right;" do %>
              <i class="mini-ico-list"></i>
            <% end %>
          </div>
          <div>
            <div class="row">
              <div> <%= render_breadcrumbs %> </div>
            </div>
          </div>
          <p>
            <%= @topic.description.html_safe %>
          </p>

          <%= render 'questions.html.erb' %>
        </div>
        <!-- end: About Us -->
      </div>
      <div class="span4">
        <!-- start: Sidebar -->
        <%= render "klass/sidebar" %>
        <!-- end: Sidebar -->
      </div>
    </div>
    <!--end: Row-->
  </div>
  <!--end: Container-->
</div>