config/routes.rb
Cms::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users

  root :to => 'home#index'
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :home do
    collection do
      get 'about'
    end
  end
  resources :klass, :path => "class"
  resources :subject
  resources :chapter
  resources :topics do
    member do
      get 'history'
    end
  end

  resources :questions do
    member do
      get 'history'
    end
  end

  resources :answers do
    member do
      get 'history'
    end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  has_paper_trail
  attr_accessible :description, :question_id
  belongs_to :question
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	has_paper_trail
  attr_accessible :title, :name, :description, :subject_id
  belongs_to :subject
  has_many :topics

  validates_presence_of :subject_id
  validates_uniqueness_of :name, :scope => :subject_id
end

app/models/klass.rb
class Klass < ActiveRecord::Base
	has_paper_trail
  attr_accessible :title, :name
  has_many :subjects
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_paper_trail
  attr_accessible :title, :topic_id
  belongs_to :topic
  has_many :answers
end

app/models/subject.rb
class Subject < ActiveRecord::Base
	has_paper_trail
  attr_accessible :title, :name, :klass_id
  belongs_to :klass
  has_many :chapters

  validates_presence_of :klass_id
  validates_uniqueness_of :name, :scope => :klass_id
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_paper_trail
  # attr_accessible :title, :body
  attr_accessible :title, :name, :description, :chapter_id
  belongs_to :chapter
  has_many :questions
  validates_presence_of :chapter_id, :blank => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/klass_controller.rb
class KlassController < ApplicationController
	add_breadcrumb "home", :root_path
	
	def index
		logger.info params
		logger.info cookies

		@klasses = Klass.all
		add_breadcrumb "class", klass_path
	end

	def show
		@klass = Klass.find(params[:id])
		add_breadcrumb "class", klass_path
		add_breadcrumb @klass.name, klas_path(@klass)
	end
end

app/controllers/topic_controller.rb
class TopicController < ApplicationController
	add_breadcrumb "home", :root_path
	add_breadcrumb "class", :klass_path

	def show
		@topic = Topic.find(params[:id])
		add_breadcrumb @topic.chapter.subject.klass.name, klas_path(@topic.chapter.subject.klass)
		add_breadcrumb @topic.chapter.subject.name, subject_path(@topic.chapter.subject)
		add_breadcrumb @topic.chapter.name, chapter_path(@topic.chapter)
		add_breadcrumb @topic.name, topic_path
	end

	def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
    end
	 end


	def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
	 end

	# GET /users/1/edit
	def edit
		@topic = Topic.find(params[:id])
	end

	def update
	    @topic = Topic.find(params[:id])

	    respond_to do |format|
	      if @topic.update_attributes(params[:topic])
	        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
	      else
	        format.html { render action: "edit" }
	      end
	    end
	end

	def history
		@topic = Topic.find(params[:id])
	end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	add_breadcrumb "home", :root_path
	add_breadcrumb "class", :klass_path

	def show
		@topic = Topic.find(params[:id])
		add_breadcrumb @topic.chapter.subject.klass.name, klas_path(@topic.chapter.subject.klass)
		add_breadcrumb @topic.chapter.subject.name, subject_path(@topic.chapter.subject)
		add_breadcrumb @topic.chapter.name, chapter_path(@topic.chapter)
		add_breadcrumb @topic.name, topic_path
	end

	def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
    end
	 end


	def create
    @topic = Topic.new(params[:topic])

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
	 end

	# GET /users/1/edit
	def edit
		@topic = Topic.find(params[:id])
	end

	def update
	    @topic = Topic.find(params[:id])

	    respond_to do |format|
	      if @topic.update_attributes(params[:topic])
	        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
	      else
	        format.html { render action: "edit" }
	      end
	    end
	end

	def history
		@topic = Topic.find(params[:id])
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def app_title title
		"<div id='page-title'>
		  <div id='page-title-inner'>
		    <div class='container'>
		      <h2><i class='ico-stats ico-white'></i>#{title}</h2>
		    </div>
		  </div>  
		</div>".html_safe
	end
end

app/helpers/chapter_helper.rb
module ChapterHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/klass_helper.rb
module KlassHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/layouts/_devise_footer.html.erb
<!-- start: Footer Menu -->
<div id="footer-menu" class="hidden-tablet hidden-phone">
  <!-- start: Container -->
  <div class="container">
    <!-- start: Row -->
    <div class="row">
      <!-- start: Footer Menu Logo -->
      <div class="span2">
        <div id="footer-menu-logo">
          <a href="#"><img src="/assets/logo-footer-menu.png" alt="logo" /></a>
        </div>
      </div>
      <!-- end: Footer Menu Logo -->
      <!-- start: Footer Menu Links-->
      <div class="span9">
        <div id="footer-menu-links">
          <ul id="footer-nav">
            <li><a href="index-2.html">Start</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="services.html">Services</a></li>
            <li><a href="pricing.html">Pricing</a></li>
            <li><a href="contact.html">Contact</a></li>
          </ul>
        </div>
      </div>
      <!-- end: Footer Menu Links-->
      <!-- start: Footer Menu Back To Top -->
      <div class="span1">
        <div id="footer-menu-back-to-top">
          <a href="#"></a>
        </div>
      </div>
      <!-- end: Footer Menu Back To Top -->
    </div>
    <!-- end: Row -->
  </div>
  <!-- end: Container  -->	
</div>
<!-- end: Footer Menu -->
<!-- start: Footer -->
<div id="footer">
  <!-- start: Container -->
  <div class="container">
    <!-- start: Row -->
    <div class="row">
      <!-- start: About -->
      <div class="span3">
        <h3>About Us</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
        </p>
      </div>
      <!-- end: About -->
      <!-- start: Photo Stream -->
      <div class="span3">
        <h3>We are here!</h3>
        <div id="small-map-container"><a href="contact.html"></a></div>
        <iframe id="small-map" width="210" height="210" frameborder="0" scrolling="yes" marginheight="0" marginwidth="0" src="https://maps.google.pl/maps?f=q&amp;source=s_q&amp;hl=pl&amp;geocode=&amp;q=Los+Angeles,+Kalifornia,+Stany+Zjednoczone&amp;aq=0&amp;oq=Los&amp;sll=50.143066,18.85267&amp;sspn=0.057207,0.168915&amp;t=m&amp;ie=UTF8&amp;hq=&amp;hnear=Los+Angeles,+Hrabstwo+Los+Angeles,+Kalifornia,+Stany+Zjednoczone&amp;ll=34.052234,-118.243685&amp;spn=0.036979,0.084457&amp;z=14&amp;iwloc=near&amp;output=embed"></iframe>
      </div>
      <!-- end: Photo Stream -->
      <div class="span6">
        <!-- start: Follow Us -->
        <h3>Follow Us!</h3>
        <ul class="social-grid">
          <li>
            <div class="social-item">
              <div class="social-info-wrap">
                <div class="social-info">
                  <div class="social-info-front social-twitter">
                    <a href="http://twitter.com/"></a>
                  </div>
                  <div class="social-info-back social-twitter-hover">
                    <a href="http://twitter.com/"></a>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="social-item">
              <div class="social-info-wrap">
                <div class="social-info">
                  <div class="social-info-front social-facebook">
                    <a href="http://facebook.com/"></a>
                  </div>
                  <div class="social-info-back social-facebook-hover">
                    <a href="http://facebook.com/"></a>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="social-item">
              <div class="social-info-wrap">
                <div class="social-info">
                  <div class="social-info-front social-dribbble">
                    <a href="http://dribbble.com/"></a>
                  </div>
                  <div class="social-info-back social-dribbble-hover">
                    <a href="http://dribbble.com/"></a>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="social-item">
              <div class="social-info-wrap">
                <div class="social-info">
                  <div class="social-info-front social-flickr">
                    <a href="http://flickr.com/"></a>
                  </div>
                  <div class="social-info-back social-flickr-hover">
                    <a href="http://flickr.com/"></a>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
        <!-- end: Follow Us -->
        <!-- start: Newsletter -->
        <form id="newsletter">
          <h3>Newsletter</h3>
          <p>Please leave us your email</p>
          <label for="newsletter_input">@:</label>
          <input type="text" id="newsletter_input"/>
          <input type="submit" id="newsletter_submit" value="submit">
        </form>
        <!-- end: Newsletter -->
      </div>
    </div>
    <!-- end: Row -->	
  </div>
  <!-- end: Container  -->
</div>
<!-- end: Footer -->
<!-- start: Copyright -->
<div id="copyright">
  <!-- start: Container -->
  <div class="container">
    <p>
      &copy; 2013, <a href="http://bootstrapmaster.com/" alt="Bootstrap Themes" title="Bootstrap Themes">Bootstrap Master</a>. Designed by BootstrapMaster in Poland <img src="/assets/poland2.png" alt="Poland" style="margin-top:-4px">
    </p>
  </div>
  <!-- end: Container  -->
</div>
<!-- end: Copyright -->

app/views/layouts/_footer.html.erb
<!-- start: Footer Menu -->
<div id="footer-menu" class="hidden-tablet hidden-phone">
  <!-- start: Container -->
  <div class="container">
    <!-- start: Row -->
    <div class="row">
      <!-- start: Footer Menu Logo -->
      <div class="span2">
        <div id="footer-menu-logo">
          <a href="#"><img src="/assets/logo-footer-menu.png" alt="logo" /></a>
        </div>
      </div>
      <!-- end: Footer Menu Logo -->
      <!-- start: Footer Menu Links-->
      <div class="span9">
        <div id="footer-menu-links">
          <ul id="footer-nav">
            <li><a href="index-2.html">Start</a></li>
            <li><a href="about.html">About</a></li>
            <li><a href="services.html">Services</a></li>
            <li><a href="pricing.html">Pricing</a></li>
            <li><a href="contact.html">Contact</a></li>
          </ul>
        </div>
      </div>
      <!-- end: Footer Menu Links-->
      <!-- start: Footer Menu Back To Top -->
      <div class="span1">
        <div id="footer-menu-back-to-top">
          <a href="#"></a>
        </div>
      </div>
      <!-- end: Footer Menu Back To Top -->
    </div>
    <!-- end: Row -->
  </div>
  <!-- end: Container  -->	
</div>
<!-- end: Footer Menu -->
<!-- start: Footer -->
<div id="footer">
  <!-- start: Container -->
  <div class="container">
    <!-- start: Row -->
    <div class="row">
      <!-- start: About -->
      <div class="span3">
        <h3>About Us</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
        </p>
      </div>
      <!-- end: About -->
      <!-- start: Photo Stream -->
      <div class="span3">
        <h3>We are here!</h3>
        <div id="small-map-container"><a href="contact.html"></a></div>
        <iframe id="small-map" width="210" height="210" frameborder="0" scrolling="yes" marginheight="0" marginwidth="0" src="https://maps.google.pl/maps?f=q&amp;source=s_q&amp;hl=pl&amp;geocode=&amp;q=Los+Angeles,+Kalifornia,+Stany+Zjednoczone&amp;aq=0&amp;oq=Los&amp;sll=50.143066,18.85267&amp;sspn=0.057207,0.168915&amp;t=m&amp;ie=UTF8&amp;hq=&amp;hnear=Los+Angeles,+Hrabstwo+Los+Angeles,+Kalifornia,+Stany+Zjednoczone&amp;ll=34.052234,-118.243685&amp;spn=0.036979,0.084457&amp;z=14&amp;iwloc=near&amp;output=embed"></iframe>
      </div>
      <!-- end: Photo Stream -->
      <div class="span6">
        <!-- start: Follow Us -->
        <h3>Follow Us!</h3>
        <ul class="social-grid">
          <li>
            <div class="social-item">
              <div class="social-info-wrap">
                <div class="social-info">
                  <div class="social-info-front social-twitter">
                    <a href="http://twitter.com/"></a>
                  </div>
                  <div class="social-info-back social-twitter-hover">
                    <a href="http://twitter.com/"></a>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="social-item">
              <div class="social-info-wrap">
                <div class="social-info">
                  <div class="social-info-front social-facebook">
                    <a href="http://facebook.com/"></a>
                  </div>
                  <div class="social-info-back social-facebook-hover">
                    <a href="http://facebook.com/"></a>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="social-item">
              <div class="social-info-wrap">
                <div class="social-info">
                  <div class="social-info-front social-dribbble">
                    <a href="http://dribbble.com/"></a>
                  </div>
                  <div class="social-info-back social-dribbble-hover">
                    <a href="http://dribbble.com/"></a>
                  </div>
                </div>
              </div>
            </div>
          </li>
          <li>
            <div class="social-item">
              <div class="social-info-wrap">
                <div class="social-info">
                  <div class="social-info-front social-flickr">
                    <a href="http://flickr.com/"></a>
                  </div>
                  <div class="social-info-back social-flickr-hover">
                    <a href="http://flickr.com/"></a>
                  </div>
                </div>
              </div>
            </div>
          </li>
        </ul>
        <!-- end: Follow Us -->
        <!-- start: Newsletter -->
        <form id="newsletter">
          <h3>Newsletter</h3>
          <p>Please leave us your email</p>
          <label for="newsletter_input">@:</label>
          <input type="text" id="newsletter_input"/>
          <input type="submit" id="newsletter_submit" value="submit">
        </form>
        <!-- end: Newsletter -->
      </div>
    </div>
    <!-- end: Row -->	
  </div>
  <!-- end: Container  -->
</div>
<!-- end: Footer -->
<!-- start: Copyright -->
<div id="copyright">
  <!-- start: Container -->
  <div class="container">
    <p>
      &copy; 2013, <a href="http://bootstrapmaster.com/" alt="Bootstrap Themes" title="Bootstrap Themes">Bootstrap Master</a>. Designed by BootstrapMaster in Poland <img src="/assets/poland2.png" alt="Poland" style="margin-top:-4px">
    </p>
  </div>
  <!-- end: Container  -->
</div>
<!-- end: Copyright -->

app/views/layouts/_header.html.erb
<!--start: Header -->
<header>
  <!--start: Container -->
  <div class="container">
    <!--start: Row -->
    <div class="row">
      <!--start: Logo -->
      <div class="logo span3">
        <%= link_to image_tag('images.jpeg', :alt => "logo", :width => "170px", :height => "50px"), root_url, :class => "brand" %>
        <!-- <a class="brand" href="/"><img src="/assets/logo.png" alt="Logo"></a> -->
      </div>
      <!--end: Logo -->
      <!--start: Navigation -->
      <div class="span9">
        <div class="navbar navbar-inverse">
          <div class="navbar-inner">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            </a>
            <div class="nav-collapse collapse">
              <ul class="nav">
                <li class="active">
                  <%= link_to "Home", root_url %>
                </li>
                <li><a href="/class">Class</a></li>
                <li>
                  <%= link_to "Add Topic", new_topic_path %>
                </li>
                <li><a href="contact.html">Contact</a></li>
                <% if user_signed_in? %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= current_user.email.truncate(10) %> <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
                      <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
                    </ul>
                  </li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to "Sign up", new_user_registration_path %>
                       <!--  <a >Sign up</a> -->
                      </li>
                      <li>
                        <%= link_to "Sign in", new_user_session_path %>
                        <!-- <a data-toggle="modal" data-target="#myModal">Sign in</a> -->
                      </li>
                    </ul>
                  </li>
                <% end %>
                <!-- <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Action</a></li>
                    <li><a href="#">Another action</a></li>
                    <li><a href="#">Something else here</a></li>
                    <li class="divider"></li>
                    <li class="nav-header">Nav header</li>
                    <li><a href="#">Separated link</a></li>
                    <li><a href="#">One more separated link</a></li>
                  </ul>
                </li> -->
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!--end: Navigation -->
    </div>
    <!--end: Row -->
  </div>
  <!--end: Container-->			
</header>
<!--end: Header-->

app/views/layouts/_sign_in.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for(resource, :as => resource_name, :remote => true, :url => session_path(resource_name)) do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Sign In</h4>
        </div>
        <div class="modal-body">
            <div><%= f.label :email %><br />
            <%= f.email_field :email, :autofocus => true %></div>

            <div><%= f.label :password %><br />
            <%= f.password_field :password %></div>

            <% if devise_mapping.rememberable? -%>
              <div><%= f.check_box :remember_me %> <%= f.label :remember_me %></div>
            <% end -%>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Sign in", :class => "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_sign_up.html.erb
<div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <%= form_for(resource, :as => resource_name, :remote => true, :url => registration_path(resource_name)) do |f| %>
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title" id="myModalLabel">Sign Up</h4>
        </div>
        <div class="modal-body">
          <div>
            <%= f.label :email %><br />
            <%= f.email_field :email, :autofocus => true %>
          </div>

          <div>
            <%= f.label :password %><br />
            <%= f.password_field :password %>
          </div>

          <div>
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit "Sign up", :class => "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- start: Meta -->
    <meta charset="utf-8">
    <title>GotYA FREE BOOTSTRAP THEME by BootstrapMaster</title> 
    <meta name="description" content="GotYa Free Bootstrap Theme"/>
    <meta name="keywords" content="Template, Theme, web, html5, css3, Bootstrap" />
    <meta name="author" content="Łukasz Holeczek from creativeLabs"/>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- start: Facebook Open Graph -->
    <meta property="og:title" content=""/>
    <meta property="og:description" content=""/>
    <meta property="og:type" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:image" content=""/>
    <!-- end: Facebook Open Graph -->
    <%#= stylesheet_link_tag "application", :media => "all" %>
    <link href="/assets/bootstrap.css" rel="stylesheet">
    <link href="/assets/bootstrap-responsive.css" rel="stylesheet">
    <link href="/assets/style.css" rel="stylesheet">
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
        <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
        <% end %>
        <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/content.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- start: Meta -->
    <meta charset="utf-8">
    <title>GotYA FREE BOOTSTRAP THEME by BootstrapMaster</title> 
    <meta name="description" content="GotYa Free Bootstrap Theme"/>
    <meta name="keywords" content="Template, Theme, web, html5, css3, Bootstrap" />
    <meta name="author" content="Łukasz Holeczek from creativeLabs"/>
    
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    
    <!-- start: Facebook Open Graph -->
    <meta property="og:title" content=""/>
    <meta property="og:description" content=""/>
    <meta property="og:type" content=""/>
    <meta property="og:url" content=""/>
    <meta property="og:image" content=""/>
    <!-- end: Facebook Open Graph -->
    <%#= stylesheet_link_tag "application", :media => "all" %>
    <link href="/assets/bootstrap.css" rel="stylesheet">
    <link href="/assets/bootstrap-responsive.css" rel="stylesheet">
    <link href="/assets/style.css" rel="stylesheet">
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <%= render 'layouts/header' %>
        <%= yield %>
    <%#= render 'layouts/devise_footer' %>
  </body>
</html>